# Copyright Datum Technology Corporation
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
########################################################################################################################


[ip]
paths = ["ip"]

[org]
name = "Datum"
full-name = "Datum Technology Corporation"

[project]
name        = "mio_cli"
full-name   = "Moore.io CLI Client"
description = ""

[simulation]
root-path   = "sim"
